# Site settings
title: Android Reverse note                   #你博客的标题
SEOTitle: frankpi | LiuJP       #显示在浏览器上搜索的时候显示的标题
header-img:      #显示在首页的背景图片
email: frankpi@126.com    
description: " andorid APK 逆向的一些学习过程"              #网站介绍
keyword: "Android 逆向 " #关键词
url: "https://frankpi.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写


# Sidebar settings
#sidebar: true                           # 是否开启侧边栏.
#sidebar-about-description: ""
#sidebar-avatar:/igm/avatar-by.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g


show_downloads: false
theme: jekyll-theme-cayman


# other links
twitter_username: 1
facebook_username: 1
github_username:  LiuJP
email: frankpi@126.com
weibo_username: 1
zhihu_username: 1
linkedIn_username: 1
dribbble_username: 1

description_footer: 本站记录我Android之旅的沿途风景！

gems:
  - jekyll-mentions
